export const sets = {
  one: {
    name: 'one',
    dice: 1,
    count: 0,
    points: 100,
  },
  five: {
    name: 'five',
    dice: 1,
    count: 0,
    points: 50,
  },
  threeXone: {
    name: 'threeXone',
    dice: 3,
    count: 0,
    points: 300,
  },
  threeXtwo: {
    name: 'threeXtwo',
    dice: 3,
    count: 0,
    points: 200,
  },
  threeXthree: {
    name: 'threeXthree',
    dice: 3,
    count: 0,
    points: 300,
  },
  threeXfour: {
    name: 'threeXfour',
    dice: 3,
    count: 0,
    points: 400,
  },
  threeXfive: {
    name: 'threeXfive',
    dice: 3,
    count: 0,
    points: 500,
  },
  threeXsix: {
    name: 'threeXsix',
    dice: 3,
    count: 0,
    points: 600,
  },
  fourOak: {
    name: 'fourOak',
    dice: 4,
    count: 0,
    points: 1000,
  },
  fiveOak: {
    name: 'fiveOak',
    dice: 5,
    count: 0,
    points: 2000,
  },
  sixOak: {
    name: 'sixOak',
    dice: 6,
    count: 0,
    points: 3000,
  },
  straight: {
    name: 'straight',
    dice: 6,
    count: 0,
    points: 1500,
  },
  threePairs: {
    name: 'threePairs',
    dice: 6,
    count: 0,
    points: 1500,
  },
  fourOakPair: {
    name: 'fourOakPair',
    dice: 6,
    count: 0,
    points: 1500,
  },
  twoTriplets: {
    name: 'twoTriplets',
    dice: 6,
    count: 0,
    points: 2500,
  },
};
